### ISSUE TITLE
Build fails with Config is invalid on macOS 10.12

### ISSUE THREAD

**Issue by marcelruhf** [BeatPlus/Protonmail#95]
The following output is displayed when running "npm run release":

--------------------------------------------------------------------------------------
> protonmail-desktop@0.3.0 prerelease /users/[USERNAME]/Downloads/ProtonMail
> gulp build --env=production

[15:26:03] Using gulpfile ~/Downloads/ProtonMail/gulpfile.js
[15:26:03] Starting 'bundle'...
[15:26:03] Starting 'less'...
[15:26:03] Starting 'environment'...
[15:26:03] Finished 'environment' after 2.57 ms
[15:26:03] Finished 'bundle' after 140 ms
[15:26:03] Finished 'less' after 160 ms
[15:26:03] Starting 'build'...
[15:26:03] Finished 'build' after 31 μs

> protonmail-desktop@0.3.0 release /users/[USERNAME]/Downloads/ProtonMail
> build

Error: Config is invalid:
{
  "iconUrl": "Unknown option"
}
    at /users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/src/util/readPackageJson.ts:153:11
From previous event:
    at validateConfig (/users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/out/util/readPackageJson.js:156:22)
    at /users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/src/packager.ts:130:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/out/packager.js:274:11)
    at /users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/users/[USERNAME]/Downloads/ProtonMail/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "release"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! protonmail-desktop@0.3.0 release: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the protonmail-desktop@0.3.0 release script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protonmail-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protonmail-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protonmail-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /users/[USERNAME]/.npm/_logs/2017-05-04T14_26_04_274Z-debug.log
--------------------------------------------------------------------------------------

I was able to compile it by remocinv "iconUrl" from package.json

**Comment by BeatPlus** [comment]
`Electron-builder` no longer needs iconUrl, next release will have this fixed or use the develop branch
